---
title: "Lily"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# Dashboard
library(flexdashboard)

# Manipular as tabelas
library(dplyr)

# Gráficos
library(ggplot2)
library(plotly)

# Pegar dados financeiros
library(tidyquant)
```
Column {.sidebar}
-------------------

```{r}
selectInput(
  "ticker",
  "Escolha o ticker:",
  choices = c("PETR4.SA", "BBAS3.SA", "VALE3.SA", "WEGE3.SA")
  #nome que eu estou dando ao botao
)
```



```{r download}
dados_tbl <- reactive({
  tq_get(input$ticker)
})
  
```


Column {data-width=400}
-----------------------------------------------------------------------

### Cotações

```{r}

  renderDataTable({
  dados_tbl() %>% 
  select(date, adjusted) %>% 
  arrange(desc(date))
  })

```

Column {data-width=600}
-----------------------------------------------------------------------

### Gráfico

```{r}
renderPlotly({
dados_tbl() %>% 
ggplot(aes(x = date, y = adjusted)) +
geom_line(color = "purple")  
  
})
  
```

